TravelBlog/Models/Experience.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TravelBlog.Models;


namespace TravelBlog.Models
{
    [Table("Experiences")]
    public class Experience
    {
        public Experience()
        {
            this.People = new HashSet<People>();
        }

        [Key]
        public int ExperienceId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int LocationId { get; set; }
        public virtual ICollection<People> People { get; set; }
        public virtual Location Locations { get; set; }
    }

}

TravelBlog/Controllers/ExperienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TravelBlog.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TravelBlog.Controllers
{
    public class ExperienceController : Controller
    {
        public TravelBlogContext db = new TravelBlogContext();
       
        public IActionResult Index()
        {
            
            return View(db.Experiences.Include(experiences => experiences.Locations).ToList());
        }

        public IActionResult Create()
        {
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationCity", "LocationCountry");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Experience Experience)
        {
            db.Experiences.Add(Experience);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var thisExperience = db.Experiences.Include(experiences => experiences.People)
                                   .FirstOrDefault(experiences => experiences.ExperienceId == id);
            return View(thisExperience);
        }

        public IActionResult Delete(int id)
        {
            var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            return View(thisExperience);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
			var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            db.Experiences.Remove(thisExperience);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationCity", "LocationCountry");
            return View(thisExperience);
        }

        [HttpPost]
        public IActionResult Edit(Experience experience)
        {
            db.Entry(experience).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TravelBlog/Views/Experience/Create.cshtml
@model TravelBlog.Models.Experience

@{
    ViewData["Title"] = "Experiences - Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create a new Experience</h1>

@using(Html.BeginForm())
{
    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)

    @Html.LabelFor(model => model.Description)
    @Html.TextAreaFor(model => model.Description)

    @Html.DropDownList("LocationId")

    <input type="submit" value="Create" />
}

<p>@Html.ActionLink("Back to Experiences", "Index")</p>

TravelBlog/Views/Experience/Delete.cshtml
@model TravelBlog.Models.Experience

@{
    ViewData["Title"] = "Experience - Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete @Html.DisplayFor(model => model.Title)?</h1>

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-danger">
}

@Html.ActionLink("Back to list", "Index")

TravelBlog/Views/Experience/Details.cshtml
@model TravelBlog.Models.Experience

@{
    ViewData["Title"] = "Experience - Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details for @Html.DisplayFor(model => model.Title)</h1>
<hr />
<p>Description: @Html.DisplayFor(model => model.Description)</p>

<h3>People that I experienced this with:</h3>

<table class="table">	           

    @foreach(var person in Model.People)
	{
    	<tr>
		    <th>@Html.DisplayFor(model => person.Name)</th>
        </tr>
	}
</table>

<button>@Html.ActionLink("Back to list", "Index")</button>

TravelBlog/Views/Experience/Edit.cshtml
@model TravelBlog.Models.Experience

@{
    ViewData["Title"] = "Experience - Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit @Html.DisplayFor(model => model.Title)</h1>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ExperienceId)

    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)

    @Html.DropDownList("LocationId")

    <input type="submit" class="btn btn-info" value="Save" />
}
@Html.ActionLink("Back to list", "Index")

TravelBlog/Views/Experience/Index.cshtml
@model IEnumerable<TravelBlog.Models.Experience>

@{
    ViewData["Title"] = "Experiences";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Experiences</h1>

<table class="table table-striped">
	<tr>
		<th>@Html.DisplayNameFor(model => model.Title)</th>
		<th>@Html.DisplayNameFor(model => model.Description)</th>
		<th>@Html.DisplayNameFor(model => model.Locations.LocationCity)</th>
		<th>@Html.DisplayNameFor(model => model.Locations.LocationCountry)</th>
		<th>Delete</th>
		<th>Edit</th>
	</tr>

    @foreach(var experience in Model)
	{
        <tr>
		    <td>@Html.DisplayFor(model => experience.Title)</td>
    		<td>@Html.DisplayFor(model => experience.Description)</td>
    		<td>@Html.DisplayFor(model => experience.Locations.LocationCity)</td>
    		<td>@Html.DisplayFor(model => experience.Locations.LocationCountry)</td>
		    <td><button class="btn btn-info">@Html.ActionLink("X", "Delete", new { id = experience.ExperienceId})</button></td>
		    <td><input type="button" class="btn btn-warning" value="Edit" onclick="location.href='@Url.Action("Edit", "Experience", new {id = experience.ExperienceId})'" /></td>
	    </tr>
	}
</table>

<button>@Html.ActionLink("Create new experience", "Create")</button>